version: '3'
services:
  myapp:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome:4.9.1-20230508
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 2g
    restart: unless-stopped

